queue_rules:
  - name: default
    queue_conditions:
      - base=master
      - label=S:automerge
    merge_conditions:
      - base=master
      - label=S:automerge
    merge_method: squash

pull_request_rules:
  - name: automerge to master with label S:automerge and branch protection passing
    conditions: []
    actions:
      queue:
