version: 2
jobs:
  build:
    docker:
      - image: tendermintdev/docker-tm-db-testing

    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run:
          name: test
          command: |
            make test-all
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
