name: Check links
on: [pull_request]
jobs:
  lint:
    - uses: actions/setup-go@master
      id: go
      with:
        go-version: 1.14
      # - name: Setup env for GO
      # #  this is only used until the setup-go action is updated
      #   run: |
      #     echo "::set-env name=GOPATH::$(go env GOPATH)"
      #     echo "::add-path::$(go env GOPATH)/bin"
      #     echo "::set-env name=GO111MODULE::"on""
      shell: bash
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1.1.0
    - name: Run GolangCI-Lint Action by building from repository
      uses: matoous/golangci-lint-action@v1.1.0
